# Generated by Django 2.2.12 on 2021-02-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.CharField(max_length=5000, null=True, verbose_name='信息'),
        ),
    ]
