# Generated by Django 2.2.12 on 2021-02-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210220_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.ImageField(null=True, upload_to='pic'),
        ),
    ]
